exclude:
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md
- dap.md
- uxtesting.md
- work
- ".sass-cache"

# defaults
defaults:
  -
    scope:
      path: ""
      type: agencies
    values:
      layout: default

collections:
  agencies:
    output: false
    permalink: /:path/
  data_pages:
    output: false
    permalink: /:path/data/

# Site title and description
title: "analytics.wsu.edu | Washington State University web traffic."
description: ""

# Site's own URL
url: https://analytics.wsu.edu

# Default dropdown title, will not appear if there are no sub-pages
dropdown_title: All Participating Websites

# Default data url
data_url: https://analytics.wsu.edu/data/live

# GitHub information
org_name: washingtonstateuniversity
repo_name: analytics.wsu.edu

# twitter information
twitter: wsupullman

sass:
  sass_dir: sass
  style: nested
