exclude:
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md
- dap.md
- uxtesting.md
- work
- ".sass-cache"

# defaults
defaults:
  -
    scope:
      path: ""
      type: agencies
    values:
      layout: default

# Site title and description
title: "Web Analytics | Washington State University"
description: "Displays real time web traffic at WSU and provides insight into the technology used by WSU visitors over the last 90 days."

# Site's own URL
url: https://analytics.wsu.edu

# Default dropdown title, will not appear if there are no sub-pages
dropdown_title: All Participating Websites

# Default data url
data_url: https://analytics.wsu.edu/data/live

# GitHub information
org_name: washingtonstateuniversity
repo_name: analytics.wsu.edu

# twitter information
twitter: wsupullman

sass:
  sass_dir: sass
  style: nested
